### ISSUE TITLE
If nodejs binding is enabled in a multilib build mraa and upm recipes will fail

### ISSUE THREAD

**Issue by whbruce** [ostroproject/meta-intel-iot-middleware#14]
In Multilib builds `${libdir}` is set to /usr/lib64 so /usr/lib/node_modules is not included in `FILES`.
This causes a QA error in do_package due to files in /usr/lib/node_modules.

To fix this `FILES_node-${PN}` should include `${prefix}/lib/node_modules` instead of `${libdir}/node_modules`

**Comment by tripzero** [comment]
Should mraa be installing node modules to ${libdir}?

**Comment by whbruce** [comment]
In a multilib build, mraa makefile will **not** install files to ${libdir}/node_modules so FILES must be updated accordingly. See update to initial comment.

**Comment by tripzero** [comment]
closing.  Please reopen if problem manifests again.
